export const FontFamily = [
  { value: 'Arial', optCss: "font-family:'Arial', serif;font-size:18px" },
  { value: 'Cascadia Code', optCss: "font-family:'Cascadia Code', serif;font-size:18px" },
  { value: 'Consolas', optCss: "font-family:'Consolas', serif;font-size:18px" },
  { value: 'DejaVu Sans Mono', optCss: "font-family:'DejaVu Sans Mono', serif;font-size:18px" },
  { value: 'Droid Sans', optCss: "font-family:'Droid Sans', serif;font-size:18px" },
  { value: 'Fira Sans', optCss: "font-family:'Fira Sans', serif;font-size:18px" },
  { value: 'Fira Code', optCss: "font-family:'Fira Code', serif;font-size:18px" },
  { value: 'Hack', optCss: "font-family:'Hack', serif;font-size:18px" },
  { value: 'Helvetica Neue', optCss: "font-family:'Helvetica Neue', serif;font-size:18px" },
  { value: 'Inter', optCss: "font-family:'Inter', serif;font-size:18px" },
  { value: 'JetBrains Mono', optCss: "font-family:'JetBrains Mono', serif;font-size:18px" },
  { value: 'Menlo', optCss: "font-family:'Menlo', serif;font-size:18px" },
  { value: 'Roboto', optCss: "font-family:'Roboto', serif;font-size:18px" },
  { value: 'Oxygen', optCss: "font-family:'Oxygen', serif;font-size:18px" },
  { value: 'sans-serif', optCss: "font-family:'sans-serif', serif;font-size:18px" },
  { value: 'Segoe UI', optCss: "font-family:'Segoe UI', serif;font-size:18px" },
  { value: 'SimHei', optCss: "font-family:'SimHei', serif;font-size:18px" },
  { value: 'Source Code Pro', optCss: "font-family:'Source Code Pro', serif;font-size:18px" },
  { value: 'Ubuntu', optCss: "font-family:'Ubuntu', serif;font-size:18px" },
  { value: 'Ubuntu Mono', optCss: "font-family:'Ubuntu Mono', serif;font-size:18px" },
  { value: 'Helvetica', optCss: "font-family:'Helvetica', serif;font-size:18px" },
  { value: 'Verdana', optCss: "font-family:'Verdana', serif;font-size:18px" },
  { value: 'Geneva', optCss: "font-family:'Geneva', serif;font-size:18px" },
  { value: 'Tahoma', optCss: "font-family:'Tahoma', serif;font-size:18px" },
  { value: 'Trebuchet MS', optCss: "font-family:'Trebuchet MS', serif;font-size:18px" },
  { value: '黑体', optCss: "font-family:'SimHei', serif;font-size:18px" },
  { value: '宋体', optCss: "font-family:'SimSun', serif;font-size:18px" },
  { value: '新宋体', optCss: "font-family:'NSimSun', serif;font-size:18px" },
  { value: '仿宋', optCss: "font-family:'FangSong', serif;font-size:18px" },
  { value: '楷体', optCss: "font-family:'KaiTi', serif;font-size:18px" },
  { value: '微软雅黑', optCss: "font-family:'Microsoft YaHei', serif;font-size:18px" },
  { value: '隶书', optCss: "font-family:'LiSu', serif;font-size:18px" },
  { value: '幼圆', optCss: "font-family:'YouYuan', serif;font-size:18px" },
  { value: '华文细黑', optCss: "font-family:'STXihei', serif;font-size:18px" },
  { value: '华文楷体', optCss: "font-family:'STKaiti', serif;font-size:18px" },
  { value: '华文楷体', optCss: "font-family:'STKaiti', serif;font-size:18px" },
  { value: '华文宋体', optCss: "font-family:'STSong', serif;font-size:18px" },
  { value: '华文中宋', optCss: "font-family:'STZhongsong', serif;font-size:18px" },
  { value: '华文仿宋', optCss: "font-family:'STFangsong', serif;font-size:18px" },
  { value: '方正舒体', optCss: "font-family:'FZShuTi', serif;font-size:18px" },
  { value: '方正姚体', optCss: "font-family:'FZYaoti', serif;font-size:18px" },
  { value: '华文彩云', optCss: "font-family:'STCaiyun', serif;font-size:18px" },
  { value: '华文琥珀', optCss: "font-family:'STHupo', serif;font-size:18px" },
  { value: '华文隶书', optCss: "font-family:'STLiti', serif;font-size:18px" },
  { value: '华文行楷', optCss: "font-family:'STXingkai', serif;font-size:18px" },
  { value: '华文新魏', optCss: "font-family:'STXinwei', serif;font-size:18px" },
  { value: '华文黑体', optCss: "font-family:'STHeiti', serif;font-size:18px" }
]
