rmdir /S /Q /Y "out\renderer\src\lib"
mkdir "out\renderer\src\lib"
xcopy /S /E /Y /I "src\renderer\src\lib" "out\renderer\src\lib"

rmdir /S /Q /Y "out\renderer\src\dialogs"
mkdir "out\renderer\src\dialogs"
xcopy /S /E /Y /I "src\renderer\src\dialogs" "out\renderer\src\dialogs"

rmdir /S /Q /Y "out\renderer\src\style"
mkdir "out\renderer\src\style"
xcopy /S /E /Y /I "src\renderer\src\style" "out\renderer\src\style"

del "out\BaiZeNotes.ico"
copy "icon\BaiZeNotes.ico" "out\BaiZeNotes.ico"
copy "icon\baize_icon.ico" "out\baize_icon.ico"
copy "icon\baize_icon_1.ico" "out\baize_icon_1.ico"
copy "icon\baize_calligraphy_icon.ico" "out\baize_calligraphy_icon.ico"
copy "icon\baize_cursive_icon.ico" "out\baize_cursive_icon.ico"
copy "icon\baize_spaced_icon.ico" "out\baize_spaced_icon.ico"
copy "icon\baize_clear_icon.ico" "out\baize_clear_icon.ico"
copy "icon\baize_text_icon.ico" "out\baize_text_icon.ico"
copy "icon\white_icon.ico" "out\white_icon.ico"
copy "icon\white_simple_icon.ico" "out\white_simple_icon.ico"
copy "icon\white_leaf_icon.ico" "out\white_leaf_icon.ico"
copy "icon\white_leaf_border_icon.ico" "out\white_leaf_border_icon.ico"
