import { flowchart } from './flowchart'
import { blockDiagram } from './blockDiagram'
import { C4Context } from './C4Context'
import { classDiagram } from './classDiagram'
import { erDiagram } from './erDiagram'
import { gantt } from './gantt'
import { gitGraph } from './gitGraph'
import { graph } from './graph'
import { journey } from './journey'
import { mindmap } from './mindmap'
import { packet } from './packet'
import { pie } from './pie'
import { quadrantChart } from './quadrantChart'
import { requirementDiagram } from './requirementDiagram'
import { sankey } from './sankey'
import { sequenceDiagram } from './sequenceDiagram'
import { stateDiagram } from './stateDiagram'
import { timeline } from './timeline'
import { xychart } from './xychart'
import { zenuml } from './zenuml'

export const mermaidDiagrams: MenuContext[] = [
  { label: '基础框架', context: '\n```mermaid\n\n```\n\n' },
  { label: 'flowchart', context: flowchart },
  { label: 'BlockDiagram', context: blockDiagram },
  { label: 'C4图', context: C4Context },
  { label: '类图', context: classDiagram },
  { label: '实体关系图', context: erDiagram },
  { label: '甘特图', context: gantt },
  { label: 'Git图', context: gitGraph },
  { label: '基本流程图', context: graph },
  { label: '用户旅程图', context: journey },
  { label: '思维导图', context: mindmap },
  { label: 'Packet', context: packet },
  { label: '饼图', context: pie },
  { label: '象限图', context: quadrantChart },
  { label: '需求图', context: requirementDiagram },
  { label: '桑基图', context: sankey },
  { label: '序列图', context: sequenceDiagram },
  { label: '状态图', context: stateDiagram },
  { label: '时间线图', context: timeline },
  { label: 'XYChart', context: xychart },
  { label: 'Zenuml', context: zenuml }
]
